# Generated by Django 5.2 on 2026-01-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='routine',
            name='color',
            field=models.CharField(default='bg-indigo-500', max_length=50),
        ),
    ]
