# Generated by Django 5.2 on 2026-01-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_title_routine_name_routine_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
