# Generated by Django 5.2 on 2026-01-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_routine_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
